public class IdentificationCard { 							//object class for creating and saving student identification information
//variables
  private String name; 									//saves students name to string
  private String identificationNumber; 							//saves students id number to string
  private String school; 								//saves students school to string
  private String nl = System.getProperty("line.separator"); 				//creates new line for toString method
  private String seperator = "---------------------------------------------"; 		//seperator for readibility in the toString method
  public class ObjectList{ 								//I dont remember adding this, dunno where it came from maybe a part of the automatic conversion form replit to github
  private Object[] list = new Object[10]; 						//see line 8
  }
//constructors
  public IdentificationCard(String name, String identificationNumber, String school) { 	//constructors
    this.name = name;
    this.identificationNumber = identificationNumber;
    this.school = school;
  }
//methods
											//AUTOGENERATED SET AND GET METHODS FROM REPLIT
  public String getName() {
	 return name;
  }
  public void setName(String name) {
	 this.name = name;
  }
  public String getIdentificationNumber() {
	 return identificationNumber;
  }
  public void setIdentificationNumber(String identificationNumber) {
	 this.identificationNumber = identificationNumber;
  }
  public String getSchool() {
	 return school;
  }
  public void setSchool(String school) {
	 this.school = school;
  }
  public String getID() { 								//toString method
    return name + nl + identificationNumber + nl + school + nl + seperator;
  }
}
